version: 0.1
phases:
  install:
    runtime-versions:
      java: openjdk8
  build:
    commands:
      - echo Build started on `date`
      - mvn clean install
artifacts:
  files:
    - target/bets-api.jar