version: 0.2
phases:
  install:
    runtime-versions:
      java: openjdk8
  build:
    commands:
      - echo Build started on `date`
      - mvn clean install
artifacts:
  files:
    - target/bets-api.jar #main jar
    - src/main/resources/** #properties
    - appspec.yml #appspec for CodeDeploy agent
    - deploy/** #deploy folder with start/stop scripts
