version: 0.2
phases:
  install:
    runtime-versions:
      java: openjdk8
  build:
    commands:
      - echo Build started on `date`
      - mvn clean install
artifacts:
  files:
    - bets-api.jar
    - appspec.yml
    - deploy/**